image: node:20.11.1-bullseye-slim
stages:

  - dependencycheck


services:
  - docker:24.0.6-dind
    

owasp_dependency_check:
  stage: dependencycheck
  needs: []
  image: registry.gitlab.com/acme/containers/owasp-dependency-check:latest
  script:
    - mvn org.owasp:dependency-check-maven:check -DdataDirectory=/owasp -DfailBuildOnCVSS=8
  artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/dependency-check-report.html