image: node:20.11.1-bullseye-slim
stages:
  - Build-Push

variables:
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  CLUSTER_NAME: mycluster

services:
  - docker:24.0.6-dind

docker_build:
  image: docker
  services:
    - docker:24.0.6-dind
  stage: Build-Push
  script:
    - echo "Building Docker image..."
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CONTAINER_IMAGE .

docker_push:
  needs: [docker_build]
  image: docker
  services:
    - docker:24.0.6-dind
  stage: Build-Push
  only:
    - main
  script:
    - echo "Pushing Docker image..."
    - docker push $CONTAINER_IMAGE
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
