image: node:20.11.1-bullseye-slim
stages:

  - Analyse Dependences


variables:
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  CLUSTER_NAME: mycluster

services:
  - docker:24.0.6-dind


Analyse_Dependences:
  stage: Analyse Dependences
  image:
    name: owasp/dependency-check:latest
    entrypoint: [""]
  
  script:
    - tar -xvzf publish.tar.gz -C /tmp/
    - /usr/share/dependency-check/bin/dependency-check.sh --scan ${CI_PROJECT_DIR} --format ALL --project ${CI_PROJECT_NAME} --failOnCVSS 0
    - if [ $(grep -c "vulnerabilities" dependency-check-report.json) -gt 0 ]; then exit 2; fi
  artifacts:
    when: always 
    paths:
      - "./dependency-check-report.html"
      - "./dependency-check-report.json"
    expire_in: 1 weeks
  allow_failure: true