image: node:20.11.1-bullseye-slim
stages:

  - tests


variables:
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  CLUSTER_NAME: mycluster

services:
  - docker:24.0.6-dind

include:
  - remote: 'https://api.r2devops.io/api/r/gitlab/r2devops/hub/owasp_dependency_check@1.2.2.yaml'
