image: node:20.11.1-bullseye-slim
stages:

  - build


variables:
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  CLUSTER_NAME: mycluster

services:
  - docker:24.0.6-dind


OWASP dep check:
  image: nbaars/owasp-dependency-check-as-one
  stage: build
  script:
    # Download all dependencies so they are available for OWASP Dependency-Check
    - ./mvnw $MAVEN_CLI_OPTS dependency:copy-dependencies
    # Run the CLI and pass the current directory (automatically checked out by the Gitlab pipeline) as project to scan
    # Other options can be passed depending on your project setup (https://jeremylong.github.io/DependencyCheck/dependency-check-cli/arguments.html)
    - dependency-check --data /data --scan ./ --noupdate --disableBundleAudit --disableRubygems --failOnCVSS 8
  artifacts:
    when: always
    paths:
      # Make the project available as artifact so you can view it
      - "dependency-check-report.html"
    expire_in: 1 week