image: node:latest
stages:
  - build
  - deliver

variables:
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  CLUSTER_NAME: mycluster 

services:
  - docker:24.0.5-dind

# Publish to GitLab Package Registry
include:
  - template: Jobs/Build.gitlab-ci.yml

# CD Stage
deploy_to_staging:
  image: 
    name: alpine/helm:3.12.3
    entrypoint: [""]
  stage: deliver
  before_script:
    - apk add --no-cache curl python3 py3-pip
    - pip3 install awscli
    - echo -n "$CI_JOB_TOKEN" | helm registry login -u gitlab-ci-token --password-stdin $CI_REGISTRY

  script:
    - helm repo add gitlab-registry https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/packages/helm/stable
    - aws eks update-kubeconfig --region eu-west-1 --name $CLUSTER_NAME
    - helm upgrade --install --set image.tag=$CI_COMMIT_SHORT_SHA pingpong gitlab-registry/nodejsapp-chart --namespace staging  

