image: node:20.11.1-bullseye-slim
stages:

  - test

variables:
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  CLUSTER_NAME: mycluster

services:
  - docker:24.0.6-dind


trivy:
  stage: test
  image: docker:stable-git
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CONTAINER_IMAGE . 
    - wget https://github.com/aquasecurity/trivy/releases/download/v0.49.1/trivy_0.49.1_Linux-64bit.tar.gz
    - tar zxvf trivy_0.49.1_Linux-64bit.tar.gz
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - ./trivy image $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG --exit-code 0 --severity HIGH --no-progress trivy-ci-test
    - ./trivy image $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG —exit-code 1 — severity CRITICAL — no-progress trivy-ci-test  