image: node:20.11.1-bullseye-slim
stages:

  - dependencycheck


variables:
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  CLUSTER_NAME: mycluster

services:
  - docker:24.0.6-dind


dependencycheck:
    stage: dependencycheck
    image:
        name: owasp/dependency-check
        entrypoint: [""]
#    before_script:
#        - mkdir data
#        - mkdir dependency-check
    script:
        - Dependency-Check -s . --nvdApiKey e043b5d6-0bdc-44f2-b335-2335ade6085a --failOnCVSS 7