image: node:20.11.1-bullseye-slim
stages:
  - unit-test
  - build
  - test


variables:
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  CLUSTER_NAME: mycluster

services:
  - docker:24.0.6-dind

unit-test-dependencies:
  stage: unit-test
  script:
    - echo "Installing dependencies for unit-tests"
    - npm install supertest mocha --save-dev
    - npm install jsdom --save-dev
    - npm install -y

#Performing Continous Integration
#Unit-Tests
unit_testing:
  needs: [unit-test-dependencies] 
  stage: unit-test
  script:
    - echo "Running unit tests on the application..."
    - npm test

include:
  - template: Jobs/Build.gitlab-ci.yml
  - template: Jobs/Container-Scanning.gitlab-ci.yml

container_scanning:
  variables:
    CS_DEFAULT_BRANCH_IMAGE: $CI_REGISTRY_IMAGE/$CI_DEFAULT_BRANCH:$CI_COMMIT_SHA

filesystem:
  stage: test
  image:
    name: aquasec/trivy:latest
    entrypoint: []
  script:
    - trivy fs .
