image: node:20.11.1-bullseye-slim
stages:

  - dependencycheck


services:
  - docker:24.0.6-dind

dependencycheck:
    stage: dependencycheck
    image:
        name: owasp/dependency-check
        entrypoint: [""]
#    before_script:
#        - mkdir data
#        - mkdir dependency-check
    script:
        - /usr/share/dependency-check/bin/dependency-check.sh --project Test --out . --scan . --nvdApiKey e043b5d6-0bdc-44f2-b335-2335ade6085a --enableExperimental --failOnCVSS 7
    artifacts:
      paths:
        - $CI_PROJECT_DIR/docs
    