image: node:20.11.1-bullseye-slim
stages:

  - deliver


variables:
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  CLUSTER_NAME: mycluster

services:
  - docker:24.0.6-dind


# CD Stage
deploy_to_staging:
  image: 
    name: alpine/helm:3.12.3
    entrypoint: [""]
  stage: deliver
  before_script:
    - apk add --no-cache curl python3 py3-pip
    - pip3 install awscli
    - echo -n "$CI_JOB_TOKEN" | helm registry login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_DEFAULT_REGION

  script:
    - helm repo add gitlab-registry https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/packages/helm/stable
    - aws eks update-kubeconfig --region us-east-1 --name $CLUSTER_NAME
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        helm upgrade --install --set image.tag=$CI_COMMIT_TAG mynodejsapp gitlab-registry/pingpong-chart --namespace staging  
      else
        helm upgrade --install --set image.tag=$CI_COMMIT_SHORT_SHA mynodejsapp gitlab-registry/pingpong-chart --namespace staging  
      fi